In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import warnings

In [2]:
warnings.filterwarnings('ignore', category=FutureWarning)
pd.set_option('display.max_columns', None)
sns.set(style="whitegrid")
%matplotlib inline

In [3]:
train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')
data_dict = pd.read_csv('data/data_dictionary.csv')

In [4]:
display(train.head())
print(f"Train shape: {train.shape}")

,id,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,Physical-Waist_Circumference,Physical-Diastolic_BP,Physical-HeartRate,Physical-Systolic_BP,Fitness_Endurance-Season,Fitness_Endurance-Max_Stage,Fitness_Endurance-Time_Mins,Fitness_Endurance-Time_Sec,FGC-Season,FGC-FGC_CU,FGC-FGC_CU_Zone,FGC-FGC_GSND,FGC-FGC_GSND_Zone,FGC-FGC_GSD,FGC-FGC_GSD_Zone,FGC-FGC_PU,FGC-FGC_PU_Zone,FGC-FGC_SRL,FGC-FGC_SRL_Zone,FGC-FGC_SRR,FGC-FGC_SRR_Zone,FGC-FGC_TL,FGC-FGC_TL_Zone,BIA-Season,BIA-BIA_Activity_Level_num,BIA-BIA_BMC,BIA-BIA_BMI,BIA-BIA_BMR,BIA-BIA_DEE,BIA-BIA_ECW,BIA-BIA_FFM,BIA-BIA_FFMI,BIA-BIA_FMI,BIA-BIA_Fat,BIA-BIA_Frame_num,BIA-BIA_ICW,BIA-BIA_LDM,BIA-BIA_LST,BIA-BIA_SMM,BIA-BIA_TBW,PAQ_A-Season,PAQ_A-PAQ_A_Total,PAQ_C-Season,PAQ_C-PAQ_C_Total,PCIAT-Season,PCIAT-PCIAT_01,PCIAT-PCIAT_02,PCIAT-PCIAT_03,PCIAT-PCIAT_04,PCIAT-PCIAT_05,PCIAT-PCIAT_06,PCIAT-PCIAT_07,PCIAT-PCIAT_08,PCIAT-PCIAT_09,PCIAT-PCIAT_10,PCIAT-PCIAT_11,PCIAT-PCIAT_12,PCIAT-PCIAT_13,PCIAT-PCIAT_14,PCIAT-PCIAT_15,PCIAT-PCIAT_16,PCIAT-PCIAT_17,PCIAT-PCIAT_18,PCIAT-PCIAT_19,PCIAT-PCIAT_20,PCIAT-PCIAT_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday,sii
0,00008ff9,Fall,5,0,Winter,51.0,Fall,16.877316,46.0,50.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fall,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,7.0,0.0,6.0,0.0,6.0,1.0,Fall,2.0,2.66855,16.8792,932.498,1492.00,8.25598,41.5862,13.8177,3.06143,9.21377,1.0,24.4349,8.89536,38.9177,19.5413,32.6909,NaN,NaN,NaN,NaN,Fall,5.0,4.0,4.0,0.0,4.0,0.0,0.0,4.0,0.0,0.0,4.0,0.0,4.0,4.0,4.0,4.0,4.0,4.0,2.0,4.0,55.0,NaN,NaN,NaN,Fall,3.0,2.0
1,000fd460,Summer,9,0,NaN,NaN,Fall,14.035590,48.0,46.0,22.0,75.0,70.0,122.0,NaN,NaN,NaN,NaN,Fall,3.0,0.0,NaN,NaN,NaN,NaN,5.0,0.0,11.0,1.0,11.0,1.0,3.0,0.0,Winter,2.0,2.57949,14.0371,936.656,1498.65,6.01993,42.0291,12.8254,1.21172,3.97085,1.0,21.0352,14.97400,39.4497,15.4107,27.0552,NaN,NaN,Fall,2.340,Fall,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Fall,46.0,64.0,Summer,0.0,0.0
2,00105258,Summer,10,1,Fall,71.0,Fall,16.648696,56.5,75.6,NaN,65.0,94.0,117.0,Fall,5.0,7.0,33.0,Fall,20.0,1.0,10.2,1.0,14.7,2.0,7.0,1.0,10.0,1.0,10.0,1.0,5.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Summer,2.170,Fall,5.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,2.0,2.0,1.0,1.0,28.0,Fall,38.0,54.0,Summer,2.0,0.0
3,00115b9f,Winter,9,0,Fall,71.0,Summer,18.292347,56.0,81.6,NaN,60.0,97.0,117.0,Summer,6.0,9.0,37.0,Summer,18.0,1.0,NaN,NaN,NaN,NaN,5.0,0.0,7.0,0.0,7.0,0.0,7.0,1.0,Summer,3.0,3.84191,18.2943,1131.430,1923.44,15.59250,62.7757,14.0740,4.22033,18.82430,2.0,30.4041,16.77900,58.9338,26.4798,45.9966,NaN,NaN,Winter,2.451,Summer,4.0,2.0,4.0,0.0,5.0,1.0,0.0,3.0,2.0,2.0,3.0,0.0,3.0,0.0,0.0,3.0,4.0,3.0,4.0,1.0,44.0,Summer,31.0,45.0,Winter,0.0,1.0
4,0016bb22,Spring,18,1,Summer,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Summer,1.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Train shape: (3960, 82)

In [5]:
PCIAT_cols = [f'PCIAT-PCIAT_{i+1:02d}' for i in range(20)]
def recalculate_sii(row):
    if pd.isna(row['PCIAT-PCIAT_Total']):
        return np.nan
    max_possible = row['PCIAT-PCIAT_Total'] + row[PCIAT_cols].isna().sum() * 5
    if row['PCIAT-PCIAT_Total'] <= 30 and max_possible <= 30:
        return 0
    elif 31 <= row['PCIAT-PCIAT_Total'] <= 49 and max_possible <= 49:
        return 1
    elif 50 <= row['PCIAT-PCIAT_Total'] <= 79 and max_possible <= 79:
        return 2
    elif row['PCIAT-PCIAT_Total'] >= 80 and max_possible >= 80:
        return 3
    return np.nan

train['recalc_sii'] = train.apply(recalculate_sii, axis=1)

In [6]:
mismatch_rows = train[
    (train['recalc_sii'] != train['sii']) & train['sii'].notna()
]

mismatch_rows[PCIAT_cols + [
    'PCIAT-PCIAT_Total', 'sii', 'recalc_sii'
]].style.applymap(
    lambda x: 'background-color: #FFC0CB' if pd.isna(x) else ''
)

In [7]:
train = train.dropna(subset =["recalc_sii"])

In [8]:
train['sii'] = train['recalc_sii']
train['complete_resp_total'] = train['PCIAT-PCIAT_Total'].where(
    train[PCIAT_cols].notna().all(axis=1), np.nan
)

train.drop(columns='recalc_sii', inplace=True)

In [9]:
train = train.dropna(subset =['complete_resp_total'])

In [10]:
train.shape

(2671, 83)

In [11]:
train['complete_resp_total'].isna().sum()

0

In [12]:
test.columns

Index(['id', 'Basic_Demos-Enroll_Season', 'Basic_Demos-Age', 'Basic_Demos-Sex',
       'CGAS-Season', 'CGAS-CGAS_Score', 'Physical-Season', 'Physical-BMI',
       'Physical-Height', 'Physical-Weight', 'Physical-Waist_Circumference',
       'Physical-Diastolic_BP', 'Physical-HeartRate', 'Physical-Systolic_BP',
       'Fitness_Endurance-Season', 'Fitness_Endurance-Max_Stage',
       'Fitness_Endurance-Time_Mins', 'Fitness_Endurance-Time_Sec',
       'FGC-Season', 'FGC-FGC_CU', 'FGC-FGC_CU_Zone', 'FGC-FGC_GSND',
       'FGC-FGC_GSND_Zone', 'FGC-FGC_GSD', 'FGC-FGC_GSD_Zone', 'FGC-FGC_PU',
       'FGC-FGC_PU_Zone', 'FGC-FGC_SRL', 'FGC-FGC_SRL_Zone', 'FGC-FGC_SRR',
       'FGC-FGC_SRR_Zone', 'FGC-FGC_TL', 'FGC-FGC_TL_Zone', 'BIA-Season',
       'BIA-BIA_Activity_Level_num', 'BIA-BIA_BMC', 'BIA-BIA_BMI',
       'BIA-BIA_BMR', 'BIA-BIA_DEE', 'BIA-BIA_ECW', 'BIA-BIA_FFM',
       'BIA-BIA_FFMI', 'BIA-BIA_FMI', 'BIA-BIA_Fat', 'BIA-BIA_Frame_num',
       'BIA-BIA_ICW', 'BIA-BIA_LDM', 'BIA-BIA_LST', 'BIA-BIA_SMM',
       'BIA-BIA_TBW', 'PAQ_A-Season', 'PAQ_A-PAQ_A_Total', 'PAQ_C-Season',
       'PAQ_C-PAQ_C_Total', 'SDS-Season', 'SDS-SDS_Total_Raw',
       'SDS-SDS_Total_T', 'PreInt_EduHx-Season',
       'PreInt_EduHx-computerinternet_hoursday'],
      dtype='object')

In [13]:
# Identify extra columns in the training set
extra_columns = list(set(train.columns) - set(test.columns))
extra_columns.remove('sii')
extra_columns.remove('complete_resp_total')

train = train.drop(columns=extra_columns)

In [14]:
train.to_csv('data/cleaned_train.csv', index=False)

In [15]:
X_train = train.drop(columns=['sii', 'complete_resp_total', 'id'])
y_train = train['complete_resp_total']
X_train.describe

<bound method NDFrame.describe of      Basic_Demos-Enroll_Season  Basic_Demos-Age  Basic_Demos-Sex CGAS-Season  \
0                         Fall                5                0      Winter
1                       Summer                9                0         NaN
2                       Summer               10                1        Fall
3                       Winter                9                0        Fall
5                       Spring               13                1      Winter
...                        ...              ...              ...         ...
3953                      Fall                8                0         NaN
3954                    Summer                7                1         NaN
3955                      Fall               13                0      Spring
3957                      Fall               11                0      Spring
3958                    Spring               13                0      Spring

      CGAS-CGAS_Score Physical-Season  Physical-BMI  Physical-Height  \
0                51.0            Fall     16.877316             46.0
1                 NaN            Fall     14.035590             48.0
2                71.0            Fall     16.648696             56.5
3                71.0          Summer     18.292347             56.0
5                50.0          Summer     22.279952             59.5
...               ...             ...           ...              ...
3953              NaN            Fall     17.139810             52.5
3954              NaN          Summer     13.927006             48.5
3955             60.0            Fall     16.362460             59.5
3957             68.0          Winter     21.441500             60.0
3958             70.0          Winter     12.235895             70.7

      Physical-Weight  Physical-Waist_Circumference  Physical-Diastolic_BP  \
0                50.8                           NaN                    NaN
1                46.0                          22.0                   75.0
2                75.6                           NaN                   65.0
3                81.6                           NaN                   60.0
5               112.2                           NaN                   60.0
...               ...                           ...                    ...
3953             67.2                          25.0                   60.0
3954             46.6                          23.0                   65.0
3955             82.4                           NaN                   71.0
3957            109.8                           NaN                   79.0
3958             87.0                           NaN                   59.0

      Physical-HeartRate  Physical-Systolic_BP Fitness_Endurance-Season  \
0                    NaN                   NaN                      NaN
1                   70.0                 122.0                      NaN
2                   94.0                 117.0                     Fall
3                   97.0                 117.0                   Summer
5                   73.0                 102.0                      NaN
...                  ...                   ...                      ...
3953                65.0                 112.0                      NaN
3954                75.0                 105.0                      NaN
3955                70.0                 104.0                      NaN
3957                99.0                 116.0                      NaN
3958                61.0                 113.0                      NaN

      Fitness_Endurance-Max_Stage  Fitness_Endurance-Time_Mins  \
0                             NaN                          NaN
1                             NaN                          NaN
2                             5.0                          7.0
3                             6.0                          9.0
5                             NaN                          NaN
...                           ...                          ...
3953                          NaN                          NaN
3954                          NaN                          NaN
3955                          NaN                          NaN
3957                          NaN                          NaN
3958                          NaN                          NaN

      Fitness_Endurance-Time_Sec FGC-Season  FGC-FGC_CU  FGC-FGC_CU_Zone  \
0                            NaN       Fall         0.0              0.0
1                            NaN       Fall         3.0              0.0
2                           33.0       Fall        20.0              1.0
3                           37.0     Summer        18.0              1.0
5                            NaN     Summer        12.0              0.0
...                          ...        ...         ...              ...
3953                         NaN       Fall         0.0              0.0
3954                         NaN     Summer         0.0              0.0
3955                         NaN       Fall        16.0              0.0
3957                         NaN     Winter        15.0              1.0
3958                         NaN     Spring         NaN              NaN

      FGC-FGC_GSND  FGC-FGC_GSND_Zone  FGC-FGC_GSD  FGC-FGC_GSD_Zone  \
0              NaN                NaN          NaN               NaN
1              NaN                NaN          NaN               NaN
2             10.2                1.0         14.7               2.0
3              NaN                NaN          NaN               NaN
5             16.5                2.0         17.9               2.0
...            ...                ...          ...               ...
3953           NaN                NaN          NaN               NaN
3954           NaN                NaN          NaN               NaN
3955          18.0                1.0         19.9               2.0
3957          18.5                2.0         15.8               2.0
3958           NaN                NaN          NaN               NaN

      FGC-FGC_PU  FGC-FGC_PU_Zone  FGC-FGC_SRL  FGC-FGC_SRL_Zone  FGC-FGC_SRR  \
0            0.0              0.0          7.0               0.0          6.0
1            5.0              0.0         11.0               1.0         11.0
2            7.0              1.0         10.0               1.0         10.0
3            5.0              0.0          7.0               0.0          7.0
5            6.0              0.0         10.0               1.0         11.0
...          ...              ...          ...               ...          ...
3953         0.0              0.0          8.0               1.0         10.0
3954         0.0              0.0          9.0               0.0          8.5
3955        10.0              1.0          8.0               1.0          9.0
3957         0.0              0.0         10.0               1.0         10.0
3958         NaN              NaN          NaN               NaN          NaN

      FGC-FGC_SRR_Zone  FGC-FGC_TL  FGC-FGC_TL_Zone BIA-Season  \
0                  0.0         6.0              1.0       Fall
1                  1.0         3.0              0.0     Winter
2                  1.0         5.0              0.0        NaN
3                  0.0         7.0              1.0     Summer
5                  1.0         8.0              0.0     Summer
...                ...         ...              ...        ...
3953               1.0        12.0              1.0       Fall
3954               0.0         4.5              0.0       Fall
3955               1.0        12.0              1.0       Fall
3957               1.0        14.0              1.0     Winter
3958               NaN         NaN              NaN     Summer

      BIA-BIA_Activity_Level_num  BIA-BIA_BMC  BIA-BIA_BMI  BIA-BIA_BMR  \
0                            2.0      2.66855      16.8792      932.498
1                            2.0      2.57949      14.0371      936.656
2                            NaN          NaN          NaN          NaN
3                            3.0      3.84191      18.2943     1131.430
5                            2.0      4.33036      30.1865     1330.970
...                          ...          ...          ...          ...
3953                         3.0      3.20303      17.1417     1035.270
3954                         1.0      2.36680      13.6457      966.287
3955                         3.0      4.52277      16.3642     1206.880
3957                         2.0      4.41305      21.4438     1253.740
3958                         4.0      6.66168      12.2372     1414.340

      BIA-BIA_DEE  BIA-BIA_ECW  BIA-BIA_FFM  BIA-BIA_FFMI  BIA-BIA_FMI  \
0         1492.00      8.25598      41.5862       13.8177     3.061430
1         1498.65      6.01993      42.0291       12.8254     1.211720
2             NaN          NaN          NaN           NaN          NaN
3         1923.44     15.59250      62.7757       14.0740     4.220330
5         1996.45     30.21240      84.0285       16.6877    13.498800
...           ...          ...          ...           ...          ...
3953      1759.96     11.00630      52.5331       13.4004     3.741300
3954      1256.17      9.98802      45.1853       13.2315     0.414263
3955      2051.70     19.46110      70.8117       14.0629     2.301380
3957      2005.99     20.48250      75.8033       14.8043     6.639520
3958      2970.12     26.53230      92.9092       13.0684    -0.831170

      BIA-BIA_Fat  BIA-BIA_Frame_num  BIA-BIA_ICW  BIA-BIA_LDM  BIA-BIA_LST  \
0         9.21377                1.0      24.4349      8.89536      38.9177
1         3.97085                1.0      21.0352     14.97400      39.4497
2             NaN                NaN          NaN          NaN          NaN
3        18.82430                2.0      30.4041     16.77900      58.9338
5        67.97150                2.0      32.9141     20.90200      79.6982
...           ...                ...          ...          ...          ...
3953     14.66690                1.0      25.7118     15.81500      49.3301
3954      1.41470                1.0      20.0572     15.14000      42.8185
3955     11.58830                1.0      33.3709     17.97970      66.2889
3957     33.99670                2.0      33.9805     21.34030      71.3903
3958     -5.90917                2.0      41.3715     25.00540      86.2475

      BIA-BIA_SMM  BIA-BIA_TBW PAQ_A-Season  PAQ_A-PAQ_A_Total PAQ_C-Season  \
0         19.5413      32.6909          NaN                NaN          NaN
1         15.4107      27.0552          NaN                NaN         Fall
2             NaN          NaN          NaN                NaN       Summer
3         26.4798      45.9966          NaN                NaN       Winter
5         35.3804      63.1265          NaN                NaN       Spring
...           ...          ...          ...                ...          ...
3953      20.2645      36.7181          NaN                NaN         Fall
3954      18.0937      30.0453          NaN                NaN          NaN
3955      29.7790      52.8320          NaN                NaN       Winter
3957      28.7792      54.4630          NaN                NaN       Winter
3958      45.4340      67.9038          NaN                NaN       Spring

      PAQ_C-PAQ_C_Total SDS-Season  SDS-SDS_Total_Raw  SDS-SDS_Total_T  \
0                   NaN        NaN                NaN              NaN
1                 2.340       Fall               46.0             64.0
2                 2.170       Fall               38.0             54.0
3                 2.451     Summer               31.0             45.0
5                 4.110     Summer               40.0             56.0
...                 ...        ...                ...              ...
3953              3.440       Fall               41.0             58.0
3954                NaN     Summer               48.0             67.0
3955              3.260     Winter               35.0             50.0
3957              2.729     Winter               56.0             77.0
3958              3.300     Spring               33.0             47.0

     PreInt_EduHx-Season  PreInt_EduHx-computerinternet_hoursday
0                   Fall                                     3.0
1                 Summer                                     0.0
2                 Summer                                     2.0
3                 Winter                                     0.0
5                 Spring                                     0.0
...                  ...                                     ...
3953                Fall                                     2.0
3954              Summer                                     0.0
3955                Fall                                     1.0
3957                Fall                                     0.0
3958              Spring                                     1.0

[2671 rows x 58 columns]>

In [16]:
!pip install catboost

Requirement already satisfied: catboost in c:\users\uku1\.conda\envs\ids\lib\site-packages (1.2.7)
Requirement already satisfied: graphviz in c:\users\uku1\.conda\envs\ids\lib\site-packages (from catboost) (0.20.3)
Requirement already satisfied: matplotlib in c:\users\uku1\.conda\envs\ids\lib\site-packages (from catboost) (3.9.2)
Requirement already satisfied: numpy<2.0,>=1.16.0 in c:\users\uku1\.conda\envs\ids\lib\site-packages (from catboost) (1.26.4)
Requirement already satisfied: pandas>=0.24 in c:\users\uku1\.conda\envs\ids\lib\site-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in c:\users\uku1\.conda\envs\ids\lib\site-packages (from catboost) (1.14.1)
Requirement already satisfied: plotly in c:\users\uku1\.conda\envs\ids\lib\site-packages (from catboost) (5.24.1)
Requirement already satisfied: six in c:\users\uku1\.conda\envs\ids\lib\site-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\uku1\.conda\envs\ids\lib\site-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\uku1\.conda\envs\ids\lib\site-packages (from pandas>=0.24->catboost) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\uku1\.conda\envs\ids\lib\site-packages (from pandas>=0.24->catboost) (2023.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\uku1\.conda\envs\ids\lib\site-packages (from matplotlib->catboost) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\uku1\.conda\envs\ids\lib\site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\uku1\.conda\envs\ids\lib\site-packages (from matplotlib->catboost) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\uku1\.conda\envs\ids\lib\site-packages (from matplotlib->catboost) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\uku1\.conda\envs\ids\lib\site-packages (from matplotlib->catboost) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\uku1\.conda\envs\ids\lib\site-packages (from matplotlib->catboost) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\uku1\.conda\envs\ids\lib\site-packages (from matplotlib->catboost) (3.1.2)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\uku1\.conda\envs\ids\lib\site-packages (from plotly->catboost) (9.0.0)

In [17]:
from catboost import CatBoostRegressor, Pool
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

categorical_features = [
    'Basic_Demos-Enroll_Season', 'CGAS-Season', 'Physical-Season', 'Fitness_Endurance-Season','FGC-Season', 'BIA-Season', 'PAQ_A-Season', 'PAQ_C-Season',
    'PreInt_EduHx-Season', 'SDS-Season',
    'Basic_Demos-Sex',
    'FGC-FGC_CU_Zone',
    'FGC-FGC_GSND_Zone',
    'FGC-FGC_GSD_Zone',
    'FGC-FGC_PU_Zone',
    'FGC-FGC_SRL_Zone',
    'FGC-FGC_SRR_Zone',
    'FGC-FGC_TL_Zone',
    'BIA-BIA_Activity_Level_num',
    'BIA-BIA_Frame_num',
    'PreInt_EduHx-computerinternet_hoursday'
]

X_train[categorical_features] = X_train[categorical_features].astype(str)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

# Create CatBoost Pool for better handling of categorical features
train_pool = Pool(data=X_train, label=y_train, cat_features=categorical_features)
test_pool = Pool(data=X_test, label=y_test, cat_features=categorical_features)

In [18]:
# Initialize CatBoostRegressor
model = CatBoostRegressor(
    iterations=500,       # Number of boosting iterations
    learning_rate=0.1,    # Step size for weight updates
    depth=6,              # Depth of the trees
    loss_function='RMSE', # Regression problem
    verbose=50            # Print training progress every 50 iterations
)

# Train the model
model.fit(train_pool)

# Predict on the test set
y_pred = model.predict(test_pool)

# Evaluate the model
rmse = mean_squared_error(y_test, y_pred, squared=False)
print(f"Root Mean Squared Error: {rmse}")

0:	learn: 19.7985079	total: 194ms	remaining: 1m 36s
50:	learn: 15.6159681	total: 1.96s	remaining: 17.3s
100:	learn: 14.7539104	total: 3.81s	remaining: 15s
150:	learn: 13.9306819	total: 6.04s	remaining: 14s
200:	learn: 13.1570539	total: 8.56s	remaining: 12.7s
250:	learn: 12.4083915	total: 10.7s	remaining: 10.6s
300:	learn: 11.7161988	total: 12.5s	remaining: 8.26s
350:	learn: 11.1020605	total: 14.7s	remaining: 6.25s
400:	learn: 10.5473920	total: 17.3s	remaining: 4.27s
450:	learn: 10.0996468	total: 19.1s	remaining: 2.08s
499:	learn: 9.6152441	total: 21.1s	remaining: 0us
Root Mean Squared Error: 17.148989548219884

In [19]:
test[categorical_features] = test[categorical_features].astype(str)

# Prepare the test Pool
test_pool = Pool(test.drop(columns=['id']), cat_features=categorical_features)

# Predict the target values
predicted_scores = model.predict(test_pool)

# Create a DataFrame with id and predicted score
results_df = pd.DataFrame({
    'id': test['id'],  # Include the ID column
    'predicted_score': predicted_scores  # Add the predicted scores
})

results_df.head()

         id  predicted_score
0  00008ff9        37.306520
1  000fd460        14.419475
2  00105258        29.982345
3  00115b9f        22.639660
4  0016bb22        33.839251

In [20]:
# Define the function to calculate SII index
def calculate_sii(predicted_score):
    if pd.isna(predicted_score):  # Handle missing values
        return np.nan
    rounded_score = round(predicted_score)  # Round the predicted score to an integer
    if rounded_score <= 30:
        return 0
    elif 31 <= rounded_score <= 49:
        return 1
    elif 50 <= rounded_score <= 79:
        return 2
    elif rounded_score >= 80:
        return 3
    return np.nan  # Default fallback, though this shouldn't happen
# Apply the function to the predicted_score column
results_df['sii'] = results_df['predicted_score'].apply(calculate_sii)
results_df = results_df.drop(columns='predicted_score')
# Save or display the results
results_df.to_csv('submission_test.csv', index=False)
print(results_df)

          id  sii
0   00008ff9    1
1   000fd460    0
2   00105258    0
3   00115b9f    0
4   0016bb22    1
5   001f3379    0
6   0038ba98    0
7   0068a485    0
8   0069fbed    1
9   0083e397    1
10  0087dd65    0
11  00abe655    0
12  00ae59c9    1
13  00af6387    0
14  00bd4359    1
15  00c0cd71    1
16  00d56d4b    0
17  00d9913d    0
18  00e6167c    0
19  00ebc35d    1